apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aspian-employee
  clusterName: root
rules:
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - workspaces/content
  resourceNames:
  - aspian
  verbs:
  - access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aspian-employees
  clusterName: root
subjects:
- kind: User
  name: alex
- kind: User
  name: aidan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aspian-employee