apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-member
  clusterName: aspian
rules:
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - workspaces/content
  resourceNames:
  - observability
  verbs:
  - admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-member
  clusterName: aspian
subjects:
- kind: Group
  name: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-member